name: Deploy Fullstack App

on:
  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: production
      HUGGINGFACE_API_KEY: ${{ secrets.HUGGINGFACE_API_KEY }}
      OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies for client and server
        run: |
          cd client
          npm install
          cd ../server
          npm install

      - name: Build client and server
        run: |
          cd client
          npm run build
          cd ../server
          npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: client-build
          path: client/builds

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: client-build
          path: ./client/build

      - name: Deploy to Hosting Service (e.g., Heroku, DigitalOcean)
        run: |
          # Replace this with your deployment commands, e.g., Heroku CLI or other hosting service
          # e.g., heroku deploy:remote
